---
name: ci
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/devel/openqa/containers/tumbleweed:qem-bot-dev
    steps:
      - uses: actions/checkout@v3
      - name: Setup enviroment
        run: pip install -r requirements-dev.txt
      - name: Run tests + cov report
        run: make test-with-coverage
      - name: Check style
        run: make checkstyle
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
