---
name: ci
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.6'
          cache: 'pip'
      - name: Setup enviroment
        run: pip install -r requirements-dev.txt 
      - name: Run tests + cov report
        run: python3 -m pytest -v --cov=./openqabot --cov-report=xml --cov-report=term
      - name: Check style
        run: black --check ./
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml
